@baseurl=https://node-userauthentication-app.onrender.com

###
GET {{baseurl}}

## user signup ##
###
POST {{baseurl}}/user/signup
Content-Type: application/json

{
    "name":"sugreev",
    "email":"ksugreev88@gmail.com",
    "phone":8826891859,
    "role":"Admin",
    "password":"1234"
}

## verify user by sending otp on mobile ##
###
POST {{baseurl}}/user/verify/mobile
Content-Type: application/json

{
    "phone":8826891800
}

## verifying user through otp ##
###
POST {{baseurl}}/user/verify/mobile/otp
Content-Type: application/json

{
    "phone":8826891800,
    "otp":740137
}

## user login by email and password ##
###
POST {{baseurl}}/user/login
Content-Type: application/json

{
    "email":"ksugreev88@gmail.com",
    "password":"1234"
}

## verifying user by sending otp on mail ##
###

POST {{baseurl}}/user/verify/email
Content-Type: application/json

{
    "email":"ksugreev88@gmail.com"
}

## verifying user by otp through mail ##
###
POST {{baseurl}}/user/verify/email/otp
Content-Type: application/json

{
    "email":"ksugreev88@gmail.com",
    "otp":266552
}

## login via token ##
###
POST {{baseurl}}/user/login/token
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Nzk1NThhZTlkOGQ5YmM3YWM5MTYzNyIsImVtYWlsMSI6ImtzdWdyZWV2ODhAZ21haWwuY29tIiwiaWF0IjoxNjg1NjczNTM4fQ.UH90iVSt6WuPR24ptkCmjvsWe6prD-iX62YvLAle5a4


## user logout ##
###
POST {{baseurl}}/user/logout
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Nzk1NThhZTlkOGQ5YmM3YWM5MTYzNyIsImVtYWlsMSI6ImtzdWdyZWV2ODhAZ21haWwuY29tIiwiaWF0IjoxNjg1NjczNTM4fQ.UH90iVSt6WuPR24ptkCmjvsWe6prD-iX62YvLAle5a4